### ISSUE TITLE
Tracking issue: futures 0.3

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/net-wg#1]
This issue tracks high-level progress toward a final futures 0.3 release.

- [x] Start the branch

## 0.3-alpha.1 

- [ ] Work through implications of removing `Error`, https://github.com/rust-lang-nursery/net-wg/issues/3
- [ ] Work through implications of pinning, https://github.com/rust-lang-nursery/net-wg/issues/4
- [ ] Work through implications of borrowing, https://github.com/rust-lang-nursery/net-wg/issues/5

## 0.3-beta.1

- [ ] Task-local hooks, https://github.com/rust-lang-nursery/net-wg/issues/7
- [ ] Debugging hooks, https://github.com/rust-lang-nursery/net-wg/issues/6

## 0.3.0

- [ ] futures-core APIs stabilized in libcore

**Comment by jimmycuadra** [comment]
Does this change at all with the new, more conservative libs RFC?

**Comment by aturon** [comment]
Yes, updated.

**Comment by aturon** [comment]
Closing in favor of finer-grained issues.
